django_twilio_2fa/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import *


app_name = "twilio_2fa"


urlpatterns = [
    path(
        "",
        login_required(Twilio2FAStartView.as_view()),
        name="index",
    ),
    path(
        "register",
        login_required(Twilio2FARegisterView.as_view()),
        name="register"
    ),
    path(
        "change",
        login_required(Twilio2FAChangeView.as_view()),
        name="change"
    ),
    path(
        "start",
        login_required(Twilio2FAStartView.as_view()),
        name="start"
    ),
    path(
        "verify",
        login_required(Twilio2FAVerifyView.as_view()),
        name="verify"
    ),
    path(
        "success",
        login_required(Twilio2FASuccessView.as_view()),
        name="success"
    ),
    path(
        "failed",
        login_required(Twilio2FAFailedView.as_view()),
        name="failed"
    )
]

django_twilio_2fa/templates/twilio_2fa/_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
    <title>2FA</title>
  </head>
  <body class="bg-light py-5">
    <div class="container">
        <div classs="row">
            <div class="col-12 col-md-8 col-lg-4 m-auto">

                <div id="content-container" class="card shadow">
                    <div class="card-body my-4">
                        <div class="row mb-4">
                            <div class="col-12 text-center">
                                {% block header %}
                                <i class="{% block header_icon_class %}fas fa-shield-alt{% endblock %} fa-3x"></i>
                                <div class="fs-3 mt-3">
                                    {% block header_text %}Two-Factor Authentication{% endblock %}
                                </div>
                                {% endblock %}
                            </div>
                        </div>
                        {% with WIDGET_ERROR_CLASS="is-invalid" %}
                        {% block content %}Nothing to see here!{% endblock %}
                        {% endwith %}
                    </div>
                </div><!-- content-container -->

                {% if debug|length %}
                <div class="card mt-4">
                    <div class="card-header">
                        Debug Info
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled">
                            {% for key, value in debug.items %}
                            <li><strong>{{ key }}</strong>: {{ value }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endif %}

            </div>
        </div><!-- row -->
    </div><!-- container -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <style>
        body, html {
            width: 100%;
            height: 100%;
        }
    </style>
  </body>
</html>

django_twilio_2fa/templates/twilio_2fa/_form_errors.html
<div class="invalid-feedback">
{% for error in field.errors %}
    <p>{% if forloop.last %} class="mb-0"{% endif %}>{{ error|escape }}</p>
{% endfor %}
</div>

django_twilio_2fa/templates/twilio_2fa/_messages.html
{% if messages %}
<div class="row my-4 text-center">
    {% for message in messages %}
    <div class="col-12 m{% if forloop.first %}b{% elif forloop.last %}t{% else %}y{% endif %}-b text-{% if DEFAULT_MESSAGE_LEVELS.ERROR == message.level %}danger{% elif DEFAULT_MESSAGE_LEVELS.WARNING == message.level %}warning{% elif DEFAULT_MESSAGE_LEVELS.SUCCESS == message.level %}success{% else %}info{% endif %}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

django_twilio_2fa/templates/twilio_2fa/change.html
{% extends "twilio_2fa/registration_form.html" %}
{% load widget_tweaks %}

{% block content_header %}
    <div class="row mb-4">
        <div class="col-12 text-center">
            <p>
                To change the phone number associated with your two-factor authentication,
                enter your phone number below and we will verify it now.
            </p>
        </div>
    </div>
{% endblock %}

django_twilio_2fa/templates/twilio_2fa/failed.html
{% extends "twilio_2fa/_base.html" %}

{% block content %}
    <div class="row my-4">
        <div class="col-12 text-center">
            Unfortunately, we were not able to verify your identity.
            {% if not is_blocking %}You can attempt to verify your account again by clicking the button below.
            {% else %}You will not be able to proceed.{% endif %}
        </div>
    </div>
    {% if error_display or error_code %}
    <div class="row my-4 alert alert-danger">
        <div class="col-12 text-center">
            <div class="mb-3">{{ error_display }}</div>
            <span class="small">Error Code: {{ error_code }}</span>
        </div>
    </div>
    {% endif %}
    {% include "twilio_2fa/_messages.html" %}
    {% if not is_blocking %}
    <div class="row my-5">
        <div class="col-12 col-md-8 m-auto">
            <a href="{% url 'twilio_2fa:start' %}?c=1" class="btn btn-lg btn-outline-primary" style="width: 100%">
                <i class="fas fa-redo pe-2"></i>
                Retry Verification
            </a>
        </div>
    </div>
    {% endif %}
    {% if verification_id %}
    <div class="row">
        <div class="col-12 text-center small text-muted">
            If you feel this was in error or are having difficulties verifying, please contact customer support.<br><br>
            <span class="bg-light p-2">{{ verification_id }}</span>
        </div>
    </div>
    {% endif %}
{% endblock %}

django_twilio_2fa/templates/twilio_2fa/register.html
{% extends "twilio_2fa/registration_form.html" %}
{% load widget_tweaks %}

{% block content_header %}
    <div class="row mb-4">
        <div class="col-12 text-center">
            <p>
                For the safety and security of your account, we {% if is_optional %}strongly encourage{% else %}require{% endif %} you to
                setup two-factor authentication. This allows us to verify your identity using your phone.
            </p>
            <p>
                To start setting up two-factor authentication, enter your phone number below and we will verify it now.
            </p>
        </div>
    </div>
{% endblock %}

django_twilio_2fa/templates/twilio_2fa/registration_form.html
{% extends "twilio_2fa/_base.html" %}
{% load widget_tweaks %}

{% block content %}
    {% block content_header %}{% endblock %}
    {% include "twilio_2fa/_messages.html" %}
    {% if can_change|default_if_none:True %}
    <form class="form" method="post">
        <div class="row mb-4">
            <div class="col-12 m-auto">
                <div class="form-group has-validation">
                    <label for="country_code">Select your country</label>
                    {% render_field form.country_code class+="form-control" %}
                </div>
            </div>
            <div class="col-12 m-auto mt-1">
                <div class="form-group has-validation">
                    <label for="phone_number">Enter your phone number</label>
                    {% render_field form.phone_number class+="form-control" %}
                    {% include "twilio_2fa/_form_errors.html" with field=form.phone_number %}
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-6 m-auto">
                <button type="submit" class="btn btn-outline-primary" style="width: 100%">
                    Continue
                </button>
            </div>
            {% if is_optional %}
            <div class="col-6">
                <a href="{{ skip_href }}" class="btn btn-outline-secondary" style="width: 100%">
                    Skip
                </a>
            </div>
            {% endif %}
        </div>
        {% csrf_token %}
    </form>
    {% endif %}
{% endblock %}

django_twilio_2fa/templates/twilio_2fa/start.html
{% extends "twilio_2fa/_base.html" %}
{% load widget_tweaks %}

{% block content %}
    <form class="form" method="post">
        <div class="row mb-3">
            <div class="col-12 text-center">
                <p>For the security of your account, we require verification before you can continue on to our site.</p>
            </div>
        </div>
        {% include "twilio_2fa/_messages.html" %}
        <div class="row">
            <div class="col-8 border-top my-2 py-2 m-auto"></div>
        </div>
        <div class="row">
            <div class="col-12 mb-2 text-center">
                Choose a verification method:
            </div>
            {% for method in methods.values %}
            <div class="col-12 my-2 text-center">
                <button type="submit" name="method" value="{{ method.value }}" class="btn btn-outline-primary" style="width: 60%">
                    {% if method.icon %}
                    <i class="{{ method.icon }} pe-1"></i>
                    {% endif %}
                    {{ method.label }}
                </button>
            </div>
            {% endfor %}
        </div>
        {% csrf_token %}
    </form>
{% endblock %}

django_twilio_2fa/templates/twilio_2fa/success.html
{% extends "twilio_2fa/_base.html" %}
{% load widget_tweaks %}

{% block content %}
    <div class="row mb-4">
        <div class="col-12 fs-3 text-center text-success">
            {{ message }}
        </div>
    </div>
    {% include "twilio_2fa/_messages.html" %}
    <div class="row">
        <div class="col-6 m-auto">
            <a href="{{ next_url }}" class="btn btn-outline-primary" style="width: 100%">
                Continue
            </a>
        </div>
    </div>
{% endblock %}

django_twilio_2fa/templates/twilio_2fa/verify.html
{% extends "twilio_2fa/_base.html" %}
{% load widget_tweaks %}

{% block content %}
    <form class="form" method="post">
        <div class="row mb-3">
            <div class="col-12 text-center">{{ message }}</div>
        </div>
        {% include "twilio_2fa/_messages.html" %}
        {% if form.non_field_errors %}
        <div class="col-12 alert alert-danger">
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <div class="row mb-4">
            <div class="col-10 m-auto">

                <div class="row">
                    <div class="col-8">
                        {% render_field form.token class+="form-control text-center" placeholder="Enter your token here" style="width: 100%" %}
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-outline-primary" style="width: 100%">
                            Verify
                        </button>
                    </div>
                    {% if form.token.errors %}
                    <div class="col-12 invalid-feedback">
                        {{ form.token.errors }}
                    </div>
                    {% endif %}
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-12 text-center small text-muted">
                <a href="{% url 'twilio_2fa:start' %}?action=retry" class="text-reset">
                    Haven't received the
                    {% if method == "sms" %}text
                    {% elif method == "call" %}call
                    {% elif method == "whatsapp" %}message
                    {% elif method == "email" %}e-mail
                    {% else %}code{% endif %}?
                </a>
            </div>
        </div>
        {% csrf_token %}
    </form>
{% endblock %}